name: ShieldTest
packages:
  Shield:
    url: https://github.com/outfoxx/Shield.git
    from: 0.0.0
localPackages:
  - ../Shield
options:
  bundleIdPrefix: io.outfoxx
targets:
  ShieldWrap:
    type: framework.static
    platform: [macOS, iOS, tvOS, watchOS]
    deploymentTarget:
      macOS: 10.12
      iOS: 10.0
      tvOS: 10.0
      watchOS: 3.0
    sources: []
    info:
      path: Project/${platform}/Info.plist
    scheme:
      testTargets:
        - ShieldTests_${platform}
    dependencies:
      - package: Shield
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.outfoxx.ShieldWrap
  ShieldHost:
    type: application
    platform: [macOS, iOS, tvOS, watchOS]
    deploymentTarget:
      macOS: 10.12
      iOS: 10.0
      tvOS: 10.0
      watchOS: 3.0
    sources:
      - path: TestHosts/${platform}
        createIntermediateGroups: true
    info:
      path: Project/${platform}Host/Info.plist
    entitlements:
      path: Project/${platform}Host/Host.entitlements
      properties:
        keychain-access-groups: []
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.outfoxx.ShieldHost
  

  ShieldTests:
    type: bundle.unit-test
    platform: [iOS, tvOS, watchOS]
    deploymentTarget:
      iOS: 10.0
      tvOS: 10.0
      watchOS: 3.0
    sources: [Tests]
    dependencies:
      - target: ShieldWrap_${platform}
        link: true
      - target: ShieldHost_${platform}
        link: false
    settings:
      GENERATE_INFOPLIST_FILE: true
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/ShieldHost.app/ShieldHost
  
  ShieldTests_macOS:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: 10.12
    sources: [Tests]
    dependencies:
      - target: ShieldWrap_macOS
        link: true
      - target: ShieldHost_macOS
        link: false
    settings:
      GENERATE_INFOPLIST_FILE: true
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/ShieldHost.app/Contents/MacOS/ShieldHost
